### ISSUE TITLE
global replacement of UploadField with SelectUploadField stopped working

### ISSUE THREAD

**Issue by stevevu** [silverstripe/silverstripe-selectupload#11]
Hi,

(Using SS v3.1.5 and latest version of SelectUploadField)

I configured UploadField to be replaced globally by SelectUploadField a while back and it seemed to work fine.  However, this global config seemed to stop working as all UploadFields no longer have to the option to select the destination folder that SelectUploadField does.  Not sure why it stopped working.  The only thing I can think of is the upgrade to SS3.1.5, although I don't see anything in notes or commits of SelectUploadField that would suggest so.

Code wise, I just followed the documentation to set up the global replacement of UploadField with SelectUploadField.  In mysite/_config/config.yml:

```
Injector:
  UploadField: SelectUploadField
```

I also tried another config syntax I found on the Injector class' documentation page [2], but this didn't work either:

```
Injector:
  UploadField:
    class: SelectUploadField 
```

I'm instantiating an Upload field in the usual manner, hoping that SelectUploadField would replace it because of the Injector config above:

`$field = UploadField::create('MyImage', 'My Image')`

However, if I individually replace an UploadField with SelectUploadField, then I do see the select destination folder option.  So something odd has happened with the global replacement method but I can't figure out what it is.

**Comment by stevevu** [comment]
@chillu , any updates on this?  Thanks!

**Comment by EurSylvain** [comment]
Dear stevevu,
It's perfectly working for me with this syntax :

Injector:
  UploadField:
    class: SelectUploadField

In the app.yml file (not config.yml). Tested today with Silverstripe 3.5.3

**Comment by robbieaverill** [comment]
Hi @stevevu - I can't reproduce this issue with a vanilla CWP 1.6.0 (SS 3.6.0) recipe. Please feel free to reopen if you're still experiencing this and provide your full mysite config.yml
