### ISSUE TITLE
Is there any way to get this working with sortablefile?

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-selectupload#28]
In order to get drag and drop sort order on the files I've tried extending SortableUploadField
I also tried the other way around — SortableUploadField extending SelectUploadField — but in both cases select upload still works but no drag and drop reordering.

Any ideas?

**Comment by robbieaverill** [comment]
Hi @neilcreagh - I suggest you open an issue on the SortableUploadField for this
