### ISSUE TITLE
Javascript event's aren't binded when navigating between screens

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-selectupload#32]
When clicking between screens ('Add to Files / Uploads (change)' link doesn't work as expected.

My use case - DataObject has upload field, linked to page, load page in the CMS, click GridField row to edit DataObject.

**Comment by robbieaverill** [comment]
Which version are you using @wilr ?

**Comment by wilr** [comment]
6af639abbc9a889005a2556697d9ddcb922ec654

**Comment by wilr** [comment]
@robbieaverill happy to submit a patch for it - normally I used to using Entwine and `onmatch` to attach the event handlers but perhaps that's outdated now and there is a better way?

Also `handleDisplayFolderSelect` looks like it'll only ever support one instance per page rather than handling each field.

**Comment by robbieaverill** [comment]
Sorry, I haven't looked at how this module is implemented in v4 at all so can't really help :(
