### ISSUE TITLE
JavaScript Error in IE11

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-selectupload#33]
![Screenshot from 2019-10-11 14-17-28](https://user-images.githubusercontent.com/878176/66617517-ed484580-ec31-11e9-877c-98c612e89e5f.png)

Looks like this is caused by the fat arrow syntax:
https://github.com/silverstripe/silverstripe-selectupload/blob/master/js/SelectUploadField.js#L3

Which is not supported by IE11:
https://caniuse.com/#search=fat%20arrow

But the CMS should support IE11:
https://docs.silverstripe.org/en/4/getting_started/server_requirements/#cms-browser-requirements

**Comment by flashbackzoo** [comment]
Also the `forEach` will break

https://caniuse.com/#search=forEach

**Comment by Leapfrognz** [comment]
Also the use of const will break when there are multipleselectuploadfields.
`Requirements::customScript("const folderURL = '$folderLink'");`

```

</script>
  | <script type="application/javascript">//<![CDATA[
  | const folderURL = 'admin/pages/edit/EditForm/1408/field/FeaturedImage/changeFolder'
  | //]]></script>
  | <script type="application/javascript">//<![CDATA[
  | const folderURL = 'admin/pages/edit/EditForm/1408/field/FacebookImage/changeFolder'
  | //]]></script>
  | <script type="application/javascript">//<![CDATA[
  | const folderURL = 'admin/pages/edit/EditForm/1408/field/TwitterImage/changeFolder'
  | //]]></script>
  | <script type="application/javascript">//<![CDATA[
  | const folderURL = 'admin/pages/edit/EditForm/1408/field/GoogleImage/changeFolder'
  | //]]></script>
```

**Comment by maxime-rainville** [comment]
Just clarifying, are you reporting this issue against the SS4 version of the module or SS3 version?

The [SS4 version of this module not officially supported](https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/). That's not to say we won't fix it, but it's going to be much lower on our priority list.

We actually have other issues for implementing similar functionality directly in the core asset module. I'm thinking if we address these issues, than this module will probably be redundant.
* https://github.com/silverstripe/silverstripe-asset-admin/issues/759
* https://github.com/silverstripe/silverstripe-cms/issues/999

**Comment by Leapfrognz** [comment]
SS4 version. Great that this will be a feature in core one day. Thanks Maxine.

**Comment by maxime-rainville** [comment]
In all honesty, we won't fix this on the SS4 branch. So I'll just close this. Hopefully, we'll eventually get to the other two issues at some stage, but I don't know when.
