### ISSUE TITLE
Global const gets overriden when the field is used multiple times

### ISSUE THREAD

**Issue by adrexia** [silverstripe/silverstripe-selectupload#35]
This line throws js errors when multiple select upload fields are used: 

https://github.com/silverstripe/silverstripe-selectupload/blob/6af639abbc9a889005a2556697d9ddcb922ec654/src/SelectUploadField.php#L70

**Comment by wilr** [comment]
@adrexia had the same issue today in the backlog. Try my PR branch and see how that goes, I've tested locally with multiple instances and confirmed this now works for me.
